services:
  - type: web
    name: gertjanassies-dev
    runtime: static
    buildCommand: curl -sL https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin && zola build
    staticPublishPath: public
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
